version: '3'
services:

  # Client microservice
  client:
    build:
      context: ./
      dockerfile: ./apps/client/Dockerfile
    env_file:
      - ./apps/client/.env
    depends_on:
      - postgres_clients
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001

  # Doctor microservice
  doctor:
    build:
      context: ./
      dockerfile: ./apps/doctor/Dockerfile
    env_file:
      - ./apps/doctor/.env
    depends_on:
      - postgres_clients
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
  
  # Postgres clients
  postgres_clients:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_clients:/var/lib/postgresql/data

  # REDIS
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres_clients:
  redis: