INSERT INTO specialties (name)
VALUES
    ('Cardiologist'),
    ('Dermatologist'),
    ('Gastroenterologist'),
    ('Neurologist'),
    ('Orthopedic Surgeon'),
    ('Pediatrician'),
    ('Ophthalmologist'),
    ('Rheumatologist'),
    ('Urologist'),
    ('Oncologist'),
    ('Endocrinologist'),
    ('Pulmonologist'),
    ('Psychiatrist'),
    ('Nephrologist'),
    ('Radiologist'),
    ('Hematologist'),
    ('Anesthesiologist'),
    ('Gynecologist'),
    ('Dentist'),
    ('Dietitian'),
    ('Podiatrist'),
    ('Pathologist'),
    ('Allergist and Immunologist'),
    ('Infectious Disease Specialist'),
    ('Geriatrician'),
    ('Physical Medicine and Rehabilitation Specialist'),
    ('Emergency Medicine Physician'),
    ('Pain Management Specialist'),
    ('Cardiothoracic Surgeon');
