INSERT INTO specialties (name)
VALUES
    ('Cardiology'),
    ('Dermatology'),
    ('Gastroenterology'),
    ('Neurology'),
    ('Orthopedics'),
    ('Pediatrics'),
    ('Ophthalmology'),
    ('Rheumatology'),
    ('Urology'),
    ('Oncology'),
    ('Endocrinology'),
    ('Pulmonology'),
    ('Psychiatry'),
    ('Nephrology'),
    ('Radiology'),
    ('Hematology'),
    ('Anesthesiology'),
    ('Gynecology'),
    ('Dentistry'),
    ('Dietetics'),
    ('Podiatry'),
    ('Pathology'),
    ('Allergy and Immunology'),
    ('Infectious Disease'),
    ('Geriatrics'),
    ('Physical Medicine and Rehabilitation'),
    ('Emergency Medicine'),
    ('Pain Medicine'),
    ('Cardiothoracic Surgery');
